-- scheduler 데이터베이스 사용

USE `scheduler`;

-- USERS 테이블 생성

CREATE TABLE `USERS` (
    `USER_ID` INT NOT NULL,
    `NAME` VARCHAR(10) NOT NULL,
    `EMAIL` VARCHAR(40) NOT NULL,
    `CREATED_DATE` DATETIME NOT NULL,
    `MOD_DATE` DATETIME NOT NULL,
    PRIMARY KEY (`USER_ID`)
);

-- SCHEDULES 테이블 생성

CREATE TABLE `SCHEDULES` (
    `SCHEDULE_ID` INT NOT NULL,
    `PASSWORD` VARCHAR(20) NOT NULL,
    `TITLE` VARCHAR(20) NOT NULL,
    `CREATED_DATE` DATETIME NOT NULL,
    `MOD_DATE` DATETIME NOT NULL,
    `USER_ID` INT NOT NULL,
    PRIMARY KEY (`SCHEDULE_ID`),
    INDEX (`USER_ID`)
);

-- USERS 테이블의 USER_ID를 SCHEDULES 테이블의 FK로 설정

ALTER TABLE `SCHEDULES`
ADD CONSTRAINT `FK_SCHEDULES_USERS`
FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`);


-- 일정 생성
INSERT INTO scheduler.SCHEDULES (SCHEDULE_ID, PASSWORD, TITLE, CREATED_DATE, MOD_DATE, USER_ID) VALUES
(5, '12345', '책읽기', NOW(), NOW(), 2)

-- 전체 일정 조회
SELECT *
FROM scheduler.SCHEDULES
ORDER BY MOD_DATE DESC 

-- 선택 일정 조회
SELECT *
FROM scheduler.SCHEDULES
WHERE SCHEDULE_ID = 1

-- 선택한 일정 수정
UPDATE scheduler.SCHEDULES 
SET TITLE = "밥 먹기"
where SCHEDULE_ID = 1

-- 선택한 일정 삭제
DELETE FROM scheduler.SCHEDULES 
WHERE SCHEDULE_id = 1
